58 enable deletion of riddles
uzh-ase-fs24/frontend pull request #59
Opened 2024-05-07 11:38 UTC by larsuzh

if a user is inside his own profile, the delete button is displayed
<img width="386" alt="image" src="https://github.com/uzh-ase-fs24/frontend/assets/91185670/4241dcdc-8668-47a2-b3f0-9452d1c113e2">
when pressed, an alert is displayed
<img width="399" alt="image" src="https://github.com/uzh-ase-fs24/frontend/assets/91185670/e425644e-1499-4c29-9a69-e49f494dd292">

2024-05-07 15:16 UTC, flyingbeat requested changes, later dismissed
changes to fix light mode are not necessary (see comment), and position of trash icon can be improved otherwise looks great!

2024-05-07 15:16 UTC, flyingbeat commented on src/app/shared/location-riddle-post/location-riddle-post.component.html
>  				</ion-item>
I would move the whole if statement outside of the div (inside the ion-item and add slot="end" to the button

2024-05-07 15:16 UTC, flyingbeat commented on src/app/shared/location-riddle-post/location-riddle-post.component.scss
this commit: 802a4cebfd7d1919d24ab452a32b4504c0d26a6a is not necessary you can simply remove 
--color: white 

from the ion-item styles. That was wrongly set by me 😞

2024-05-07 15:56 UTC, flyingbeat commented on src/app/shared/location-riddle-post/location-riddle-post.component.html
>  				</ion-item>
maybe we could even remove the dummy profile picture so there is enough space

2024-05-08 08:58 UTC, larsuzh commented
<img width="374" alt="image" src="https://github.com/uzh-ase-fs24/frontend/assets/91185670/204496ba-9932-4cfe-8d66-75c6e3a82d78">

2024-05-08 09:03 UTC, merged