fix: disable follow button if user follows  already
uzh-ase-fs24/frontend pull request #65
Opened 2024-05-07 16:10 UTC by chrsBa

2024-05-07 16:35 UTC, flyingbeat requested changes

2024-05-07 16:35 UTC, flyingbeat commented on src/app/home/tabs/search/search.component.html
> +				</ion-card>
lets add an @empty{ section if no users were found

2024-05-07 16:35 UTC, flyingbeat commented on src/app/home/tabs/search/search.component.html
> +			@for (item of searchState.searchResults(); track item.username) {
lets display a loading spinner if the users are loading

2024-05-07 22:16 UTC, flyingbeat commented
@chrsBa I have reworked the whole network / search pages for issue #66 on the corresponding branch

I copied your changes from this PR to there. I think we can close this PR (without merging) and continue on the other branch if you are ok with it.

2024-05-08 09:04 UTC, larsuzh commented
changes moved to branch #66

2024-05-08 09:04 UTC, closed without merging